global:
  scrape_interval: 60s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "kubernetes-apiservers"

    kubernetes_sd_configs:
      - role: endpoints

    scheme: https

    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    relabel_configs:
      - source_labels:
          [
            __meta_kubernetes_namespace,
            __meta_kubernetes_service_name,
            __meta_kubernetes_endpoint_port_name,
          ]
        action: keep
        regex: default;kubernetes;https

  - job_name: "kubernetes-nodes"
    scheme: https

    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    kubernetes_sd_configs:
      - role: node

    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: internet
    static_configs:
      - targets: ["internet:9273"]

  - job_name: speedtest
    static_configs:
      - targets: ["speedtest:9273"]

  - job_name: energy
    static_configs:
      - targets: ["energy:9273"]

  - job_name: node
    static_configs:
      - targets: ["nuc-00:9100", "nuc-01:9100", "nuc-02:9100"]
