resources:
  #- bases/dashboard/
  - bases/traefik/
  - bases/rancher/
  - bases/longhorn/
  - bases/whoami/
  - bases/monitoring/prometheus/
  #- bases/monitoring/grafana/
  #- bases/monitoring/internet/
  #- bases/monitoring/speedtest/
  #- bases/monitoring/energy/
  #- bases/monitoring/node-exporter/
