namespace: monitoring
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
- name: prometheus
  files:
    - etc/prometheus.yaml