apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: monitoring-prometheus
    app.kubernetes.io/version: v2.50.1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  # Use retain to avoid accidental deleting of the data.
  storageClassName: longhorn-retain
