apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: v2.50.1
spec:
  # Make a headless service.
  clusterIP: None
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: monitoring
