apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: monitoring-prometheus
    app.kubernetes.io/version: v2.50.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance:  monitoring-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/instance: monitoring-prometheus
        app.kubernetes.io/version: v2.50.1
    spec:
      serviceAccount: prometheus
      containers:
        - name: prometheus
          image: "quay.io/prometheus/prometheus:v2.50.1"
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.path=/storage
            - --storage.tsdb.retention.time=1y
            #- --web.enable-admin-api
          # This is only informational and not necessarily needed.
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
          # ports:
          #   - containerPort: 9090
          volumeMounts:
            - name: prometheus
              mountPath: /etc/prometheus/
            - name: storage
              mountPath: /storage/
      securityContext:
        # These enable Prometheus to write to the pvc.
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      volumes:
        - name: prometheus
          configMap:
            name: prometheus
        - name: storage
          persistentVolumeClaim:
            claimName: storage
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Gi
        storageClassName: longhorn-retain
