apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
    #app.kubernetes.io/component: agent
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: "v1.7.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
      #app.kubernetes.io/component: agent
      app.kubernetes.io/instance: monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
        #app.kubernetes.io/component: agent
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/part-of: prometheus
        app.kubernetes.io/version: "v1.7.0"
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        runAsNonRoot: true
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.7.0
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --path.udev.data=/host/root/run/udev/data
            # Ignore Longhorn mounts. Only nvme0n1 and sda are real disks.
            - --collector.diskstats.device-exclude=
            - --collector.diskstats.device-include=^(nvme0n1|sda)$
            - --collector.filesystem.mount-points-exclude=^/(boot|run|dev|proc|sys|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*|cni.*|flannel.*|lo|[a-f0-9]{15})$
            - --collector.netdev.device-exclude=^(veth.*|cni.*|flannel.*|lo|[a-f0-9]{15})$
            - --web.listen-address=0.0.0.0:9100
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            # This is only informational and not necessarily needed.
            # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
            # ports:
            #   - containerPort: 9100
          livenessProbe:
            httpGet:
              path: /
              port: 9100
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: 9100
              scheme: HTTP
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host/root
              mountPropagation: HostToContainer
              readOnly: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
