apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
    #app.kubernetes.io/component: agent
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: "v1.6.1"
spec:
  # Make a headless service.
  clusterIP: None
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    app.kubernetes.io/name: node-exporter
    #app.kubernetes.io/component: agent
    app.kubernetes.io/instance: monitoring
