apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: monitoring-node-exporter
    app.kubernetes.io/version: v1.7.0
spec:
  # Make a headless service.
  clusterIP: None
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/instance: monitoring-node-exporter
