namespace: kube-system
resources:
  - service.yaml
  - ingress.yaml
  - helmchartconfig.yaml
  - tlsstore.yaml
secretGenerator:
  - name: default-cert
    files:
      - tls.crt
      - tls.key
# Kustomize does not handle hashing with TLSStore.
generatorOptions:
  disableNameSuffixHash: true
