apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/instance: immich-redis
    app.kubernetes.io/version: "7.2.3"
spec:
  type: ClusterIP
  selector:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: cache
      app.kubernetes.io/instance: immich-redis
  ports:
    - port: 6379
      targetPort: 6379
