apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/arch: amd64
      containers:
        - name: intel-gpu-plugin
          image: intel/intel-gpu-plugin:0.29.0
          args:
            - -enable-monitoring
            - -v=2
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seLinuxOptions:
              type: container_device_plugin_t
          volumeMounts:
            - mountPath: /dev/dri
              name: devfs
              readOnly: true
            - mountPath: /sys/class/drm
              name: sysfsdrm
              readOnly: true
            - mountPath: /var/lib/kubelet/device-plugins
              name: kubeletsockets
      volumes:
        - name: devfs
          hostPath:
            path: /dev/dri
        - name: sysfsdrm
          hostPath:
            path: /sys/class/drm
        - name: kubeletsockets
          hostPath:
            path: /var/lib/kubelet/device-plugins
