---
- hosts: all
  become: true

  name: Resize logical volumes

  tasks:
    - name: Resize root to 128G
      community.general.lvol:
        vg: rl
        lv: root
        size: 128g
        resizefs: true
        shrink: false
