---
- hosts: all
  become: true

  name: Resize logical volumes

  tasks:
    - name: Resize root to 64G
      community.general.lvol:
        vg: rl
        lv: root
        size: 64g
        resizefs: true
        shrink: false
