---
- name: Build a single node k3s cluster
  hosts: nuc-00
  vars:
    # Rancher needs Kubernetes < 1.27.0-0. Comment this out if
    # not using Rancher to get the latest k3s.
    k3s_release_version: v1.26.5+k3s1
    k3s_become: true
    # Rancher managed updates ie. system-upgrade-controller needs this.
    k3s_install_hard_links: true
    # Uncomment this if you want to uninstall
    #k3s_state: uninstalled
    k3s_server:
      write-kubeconfig-mode: "0644"
  roles:
    - role: xanmanning.k3s
