namespace: cattle-system
resources:
  - namespace.yaml
  - templates/clusterRoleBinding.yaml
  - templates/configMap.yaml
  - templates/deployment.yaml
  - templates/ingress.yaml
  - templates/priorityClass.yaml
  - templates/secret.yaml
  - templates/service.yaml
  - templates/serviceAccount.yaml
secretGenerator:
  # $ cp ../traefik/cacert.crt cacerts.pem
  - name: tls-ca
    files:
      - cacerts.pem
generatorOptions:
  disableNameSuffixHash: true