namespace: monitoring
resources:
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
- name: grafana-datasources
  files:
    - etc/grafana/provisioning/datasources/prometheus.yaml
