apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy
  labels:
    app.kubernetes.io/name: energy
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: monitoring-energy
    app.kubernetes.io/version: 1.27.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: energy
      app.kubernetes.io/instance: monitoring-energy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: energy
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/instance: monitoring-energy
        app.kubernetes.io/version: 1.27.4
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.27.4-alpine
          # This is only informational and not necessarily needed.
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
          # ports:
          #   - containerPort: 9273
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
