---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/instance: immich-storage
    app.kubernetes.io/version: v1.101.0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  # Use retain to avoid accidental deleting of the data.
  storageClassName: longhorn-retain
