apiVersion: v1
kind: Service
metadata:
  name: unpoller
  labels:
    app.kubernetes.io/name: unpoller
    #app.kubernetes.io/component: agent
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "v2.8.1"
spec:
  # Make a headless service.
  clusterIP: None
  ports:
    - port: 9130
      targetPort: 9130
  selector:
    app.kubernetes.io/name: unpoller
    #app.kubernetes.io/component: agent
    app.kubernetes.io/instance: monitoring
