apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet
  labels:
    app.kubernetes.io/name: internet
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: monitoring-internet
    app.kubernetes.io/version: 1.29.5
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: internet
      app.kubernetes.io/instance: monitoring-internet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: internet
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/instance: monitoring-internet
        app.kubernetes.io/version: 1.29.5
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.29.5-alpine
          # This is only informational and not necessarily needed.
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
          # ports:
          #   - containerPort: 9273
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
