apiVersion: v1
kind: Service
metadata:
  name: internet
  labels:
    app.kubernetes.io/name: internet
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: monitoring-internet
    app.kubernetes.io/version: 1.29.5
  annotations:
    # Scrape only the service not each service endpoint.
    prometheus.io/scrape: service
spec:
  # Make a headless service.
  clusterIP: None
  ports:
    - port: 9273
      targetPort: 9273
  selector:
    app.kubernetes.io/name: internet
    app.kubernetes.io/instance: monitoring-internet
