apiVersion: v1
kind: Service
metadata:
  name: internet
  labels:
    app.kubernetes.io/name: internet
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/part-of: influxdb
    app.kubernetes.io/version: "1.25.3"
  annotations:
      prometheus.io/scrape: service
spec:
  # Make a headless service.
  clusterIP: None
  ports:
    - port: 9273
      targetPort: 9273
  selector:
    app.kubernetes.io/name: internet
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/instance: monitoring
