---
# Source: openebs/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs
  labels:
    app: openebs
    chart: openebs-3.8.0
    release: openebs
    heritage: Helm
