namespace: librephotos
resources:
  #- namespace.yaml
  - pvc.yaml
  - deployment.yaml
  #- statefulset.yaml
  - service.yaml
  - ingress.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  # - redis/service.yaml
  # - redis/deployment.yaml
secretGenerator:
  - name: config
    envs:
      - config.env
